[project]
name = "ray-nccl-test"
version = "0.1.0"
description = "NCCL Performance Test on Ray"
requires-python = ">=3.10"
dependencies = [
  "torch", 
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/nightly/cu129"