[project]
name = "ray-nccl-test"
version = "0.1.0"
description = "NCCL Performance Test on Ray"
requires-python = ">=3.10"
dependencies = [
    "ray[default]",
    "torch==2.9.1",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/nightly/cu129"
default = true
